version: "3.1"

services:


# ---------------------
# Services
# ---------------------

        citrium-php:
                build: ./services/php/
                container_name: citrium-php
                ports:
                        - 9000
                volumes:
                        - ./../citrium:/var/www/citrium
                user: 1000:1000

        citrium:
                image: nginx:latest
                container_name: citrium
                ports:
                        - "80:80"
                volumes:
                        - ./../:/var/www/
                        - ./services/nginx:/etc/nginx/conf.d

# ----------------------
# Infrastructure
# ----------------------

        citrium-mysql:
                image: mysql:latest
                container_name: citrium-mysql
                command: --default-authentication-plugin=mysql_native_password
                restart: unless-stopped
                volumes:
                        - citrium_datastore:/var/lib/mysql
                ports:
                        - "3306:3306"
                environment:
                        - MYSQL_RANDOM_ROOT_PASSWORD="yes"


        citrium-redis:
                 image: redis:latest
                 container_name: citrium-redis
                 restart: unless-stopped
                 volumes: 
                        - citrium_redis:/data

# ---------------------
# Persistence Volumes
# ---------------------

volumes:
        citrium_datastore:
                driver: local
        citrium_redis:
                driver: local
